.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "AGGREGATE6" "7" "October 2015" "" ""
aggregate6 will compress an unsorted list of IPv6 prefixes\.
.
.SH "DESCRIPTION"
Takes a list of IPv6 prefixes in conventional format on stdin, and performs two optimisations to attempt to reduce the length of the prefix list\. The first optimisation is to remove any supplied prefixes which are superfluous because they are already included in another supplied prefix\. For example, \fB2001:67c:208c:10::/64\fR would be removed if \fB2001:67c:208c::/48\fR was also supplied\.
.
.P
The second optimisation identifies adjacent prefixes that can be combined under a single, shorter\-length prefix\. For example, \fB2001:67c:208c::/48\fR and \fB2001:67c:208d::/48\fR can be combined into the single prefix 2001:67c:208c::/47\.
.
.SH "INSTALLATION"
.
.nf

    $ sudo apt\-get install python\-dev
    $ sudo pip install aggregate6
.
.fi
.
.SH "USAGE"
Either provide the list of IPv6 prefixes on STDIN, or give filenames containing lists of IPv6 prefixes as arguments\.
.
.IP "" 4
.
.nf

    $ cat prefix_list | aggregate6
       \.\.\. output \.\.\.

    $ aggregate6 prefix_list [ \.\.\. optional_other_prefix_lists ]
       \.\.\. output \.\.\.

    $ echo \-e "2001:67c:208c::/48\en2000::/3" | aggregate6
    2000::/3
.
.fi
.
.IP "" 0
.
.P
See \fBaggregate6 \-h\fR for a full list of options\.
.
.SH "BUGS"
Please report bugs at: https://github\.com/job/aggregate6
.
.SH "Copyright and License"
Copyright (c) 2014, Job Snijders \fIjob@instituut\.net\fR\. All rights reserved\.
.
.P
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\.
.
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\.
.
.IP "" 0
.
.P
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\.
